### ISSUE TITLE
user problem with last update

### ISSUE THREAD

**Issue by raliseda** [dckiller51/bodymiscale#102]
Hello, I had this working with two users without any trouble, with the last update now it looks like the sensors are switching. I cannot make it work with two users. 
If I setup the first user it works ok, but when I add the second user, the firs user gets the data from the second user and viceversa.
I hope it can be fixed since it is an excellent integratio.

**Comment by Anian-igor** [comment]
I got the same issue.

**Comment by mansellrace** [comment]
I got the same issue.
