### ISSUE TITLE
Multiple profiles, age dissappear

### ISSUE THREAD

**Issue by Fonsos** [dckiller51/bodymiscale#119]
When having two profiles configured, there is an error on the widget that can get the information from the first profile, after rebooting Home Assistant, both of the profiles have no age.
Trying to edit the age is impossible, only height, weight sensor and impedance sensor can be modified.

**Comment by WalterDSU** [comment]
same problem, age is unavailable after restart.

**Comment by fliespl** [comment]
Just got into same issue. One of profiles is correct, other one has no age calculated.

**Comment by rinaldiespera** [comment]
Tried reboot option of the profile from Integration page and brought it back. However, it rendered the other bodymiscale entities for all other profiles/users unavailable. If you use Reboot option again for one particular profile/user, it brings it back but loses the entity again that is previously working.

**Comment by grego1981** [comment]
Same here, deleted and recreated the user and the age is still unavailable

**Comment by bilogic** [comment]
Is it possible to define multiprofiles on HA instead of ESPHome?
It would do away to reinstalling ESPHome each time and also make it possible to backup the profile rules in HA.

**Comment by JachinY** [comment]
I have only one profile and its age is unavailable too

**Comment by borpin** [comment]
Same here. The UI configuration makes multiple people impossible.  This is a common issue in HA.

**Comment by Hadatko** [comment]
How were you able to add more profiles? It looks like i am not able to do that :'(

**Comment by Hadatko** [comment]
Ok i was entering same age. That was the issue.

**Comment by dckiller51** [comment]
I can't reproduce the mistake. I conclude that the problem has been solved. Don't hesitate to open a new exit if the problem persists.
