### ISSUE TITLE
Manual installation not recognized

### ISSUE THREAD

**Issue by gonzavesc** [dckiller51/bodymiscale#12]
AFter copying the corresponding files to de custom_components folder, esphome still does not recognize the bodymiscale in the yaml for the board.

**Comment by dckiller51** [comment]
Hello, this components is not directly related to Esphome. You just need a sensor for the minimum weight and one for the impedance for more detail in the calculation of the score.
Can you detail your configuration?

**Comment by gonzavesc** [comment]
My current yaml is:

`esp32_ble_tracker:
sensor:
  - platform: xiaomi_miscale
    mac_address: 'C8:47:8C:9F:7B:0A'
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: weight_miscale
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state >= 69 && id(weight_miscale).state <= 94.49) {
                return id(weight_user1).publish_state(x);}
              else if (id(weight_miscale).state >= 44.50 && id(weight_miscale).state <= 73) {
                return id(weight_user2).publish_state(x);}

  - platform: template
    name: Weight Gonzalo
    id: weight_user1
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
  - platform: template
    name: Weight Victoria
    id: weight_user2
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
bodymiscale: !include components/bodymiscale.yaml`

There is an error:
![{DF6184DB-326E-4B8B-9F28-4F400C38B1EC} png](https://user-images.githubusercontent.com/43473353/119647170-41f8fe00-be20-11eb-8556-5af15637718b.jpg)

And I have the folder as you say in the readme:
![image_2021-05-26_125112](https://user-images.githubusercontent.com/43473353/119647692-de230500-be20-11eb-9b75-27de56aa795e.png)

Sorry for the inconvenience.

**Comment by dckiller51** [comment]
> Mon yaml actuel est:
> 
> `esp32_ble_tracker:
> capteur:
> 
> * plateforme: xiaomi_miscale 
>   mac_address: 'C8: 47: 8C: 9F: 7B: 0A' 
>   poids: 
>   nom: "Xiaomi Mi Scale Weight" 
>   id: weight_miscale 
>   on_value: 
>   then: 
>   - lambda: | - 
>   if (id (weight_miscale) .state> = 69 && id (weight_miscale) .state <= 94.49) { 
>   return id (weight_user1) .publish_state (x);} 
>   else if (id (weight_miscale) .state> = 44,50 && id (weight_miscale) .state <= 73) { 
>   return id (utilisateur_poids2) .publish_state (x);}
> * plate-forme: 
>   nom du modèle : poids 
>   ID Gonzalo : utilisateur_poids1 
>   unité_de_mesure: 
>   icône 'kg' : mdi: 
>   précision poids-kilogramme_decimals : 2
> * plate-forme: 
>   nom du modèle : Poids 
>   identifiant Victoria : poids_utilisateur2 
>   unité_de_mesure: 
>   icône 'kg' : mdi: poids-kilogramme 
>   precision_decimals: 2 
>   bodymiscale:! include components / bodymiscale.yaml`
> 
> Il y a une erreur:
> ![{DF6184DB-326E-4B8B-9F28-4F400C38B1EC} png](https://user-images.githubusercontent.com/43473353/119647170-41f8fe00-be20-11eb-8556-5af15637718b.jpg)
> 
> Et j'ai le dossier comme vous dites dans le readme:
> ![image_2021-05-26_125112](https://user-images.githubusercontent.com/43473353/119647692-de230500-be20-11eb-9b75-27de56aa795e.png)
> 
> Désolé pour le dérangement.

Okay I understand your mistake. Bodymiscale is a component for homeassistant. you must put in your configuration.yaml file.
