### ISSUE TITLE
Not get previous value before restart

### ISSUE THREAD

**Issue by caohuongls** [dckiller51/bodymiscale#121]
I have trouble with get previous value before restart HA.  It's display unknown for all value sensor of component and only display again after I step up Mi Scale and get the newest value on it.

**Comment by fliespl** [comment]
@caohuongls did you get this sorted out?

**Comment by caohuongls** [comment]
Look at issue #37.  It's have same issue and I find out solution to fix it. 
Just change default value "Restore state after a restart" to true in Configure of Bluetooth Low Energy Monitor
