### ISSUE TITLE
Updating documention with correct setup

### ISSUE THREAD

**Issue by fliespl** [dckiller51/bodymiscale#125]
I am having a hard time with getting proper setup.

Currently I can only set two fields (weight & impedance), but see no option to specify Date of birth / Gender in integration.

What is the correct way to do it?

**Comment by dckiller51** [comment]
In modification it does not appear. You must create a new user.

**Comment by dckiller51** [comment]
In modification it does not appear. You must create a new user.

**Comment by fliespl** [comment]
Thank you.
