### ISSUE TITLE
attributes in card not available

### ISSUE THREAD

**Issue by maverik80** [dckiller51/bodymiscale#14]
hello, after updating 0.0.6 with the card I receive everything not available on the attributes as per screenshot

![body](https://user-images.githubusercontent.com/62015384/120947137-11c62f00-c73f-11eb-95c8-9b0f1d92d1b1.png)

**Comment by dckiller51** [comment]
I also updated the card https://github.com/dckiller51/lovelace-body-miscale-card

**Comment by maverik80** [comment]
> I also updated the card https://github.com/dckiller51/lovelace-body-miscale-card

I have updated both the card and the component but everything is not available, this however without weighing me, and the old weighing

**Comment by dckiller51** [comment]
Can you show me your card configuration?

**Comment by maverik80** [comment]
> Can you show me your card configuration?

![Uploading Screenshot_2021-06-07-03-52-05-111_io.homeassistant.companion.android.jpg…]()

**Comment by maverik80** [comment]
As I suspected, with a new weigh it worked

**Comment by dckiller51** [comment]
Ah same problem via the application but works well on a browser. I am looking tomorrow.

CHROME :
![IMG_20210607_040414](https://user-images.githubusercontent.com/53062806/120949749-7e442c80-c745-11eb-84d3-79d7084d8ffe.jpg)
APP ANDROID:
![Screenshot_2021-06-07-04-03-18-439_io homeassistant companion android](https://user-images.githubusercontent.com/53062806/120949806-9e73eb80-c745-11eb-810b-cb2a4a36d05d.jpg)

**Comment by maverik80** [comment]
Thank you very much and have a nice day

**Comment by dckiller51** [comment]
It is also the cache to empty in the android application
