### ISSUE TITLE
Readme updates in the configuration

### ISSUE THREAD

**Issue by typxxi** [dckiller51/bodymiscale#15]
CONFIGURATION TABLE
#1
`plateform (Required) | string | bodymiscale
`
Typo cause you meant **`platform`**

#2
`name (Required) | string | Custom name for the sensor.&nbsp;bodymiscale.nom`
at the end it should be most likely like in the card mean name instead of nom, so **`bodymiscale.name`**

#3
Then in  the yaml file description I'd suggest to change the definition to the source sensor that is there when you had installed the miscale instead of using a specific one. I had struggled a lot, really about 10 hours to get it working simply due to my misunderstanding about the meaning of nom / name and the sensor. I did not get anything further without your help but I guess I would not have struggled if that would have been changed.

instead of `weight: sensor.weight_aurelien` then **`sensor.ble_weight_mi_scale2`**

#4
and maybe a tiny bit more explanations below these 2 settings
```
[configuration.yaml]
bodymiscale: !include components/bodymiscale.yaml
```
```
[bodymiscale.yaml]
aurelien:
  sensors:
    weight: sensor.ble_weight_mi_scale2
height: 176
...
```

> The configuration.yaml entry will create a plattform sensor called `bodymiscale`. 
> The name of the sensor itself is defined in the bodymiscale.yaml file in the first line by `aurelien:`
> 
> To check if the configruation is working properly go to the developer tools and look for the values of the 
> bodymiscale sensor by typing bodymiscale . You should see a sensor in this case called bodymicale.aurelien which has a lot of values (number of values shown is depending on your scale model).
> 

Not so many changes but will reduce the demand of support and struggles - hopefully.

**Comment by dckiller51** [comment]
I let you watch the update

**Comment by dckiller51** [comment]
Let me move your post to the card github so we have a better chance of getting other opinions and help on the card.
https://github.com/dckiller51/lovelace-body-miscale-card/issues/3
