### ISSUE TITLE
Multiple profiles are not able for twins :D

### ISSUE THREAD

**Issue by Hadatko** [dckiller51/bodymiscale#160]
Same birthday is not allowed

**Comment by Phoenix-DH** [comment]
Hey @Hadatko 

did you get managed to have more than one sensor?
How looks your implementation?

I am looking for a solution with BLE Monitor and Mi Scale 2 to have all family members is.

Thanks for a reply.

**Comment by Hadatko** [comment]
Hi this is not problem until they have same date of birth and similar weight

**Comment by Phoenix-DH** [comment]
Okay 👍🏻 

How dis you get it managed?
I have 3 Persons in BodyMiScale and all have the same sensors.

So all have the same weight because measurement then delivers the info to all.

I need a way to split this in front.

To be honest, I am pretty new in HA and still playing arround.

**Comment by Hadatko** [comment]
configuration.yml
![image](https://user-images.githubusercontent.com/13130700/219847628-2a3019c1-1e0e-4dfa-a2bd-981e7cb03023.png)

devices
![image](https://user-images.githubusercontent.com/13130700/219847670-dfc68f04-cc58-4455-a14d-6064ba2b53ef.png)

**Comment by Phoenix-DH** [comment]
You made my day 🤙🏻
Thanks a lot!

I will give it a try.

**Comment by Hadatko** [comment]
Fingers crossed ;)

**Comment by Phoenix-DH** [comment]
Did get it managed! Thanks.
Last thing I habe to check is that why some values are unavailable although they are filled in Zepp app.

**Comment by Phoenix-DH** [comment]
It is reading the values, but then I got the following only. Not all values are maintained.
I am using non_stabilized_weight because and the impendance, rest like your code:
![71ACEC88-9A72-4D3D-95BE-C609E56CD508](https://user-images.githubusercontent.com/44058592/220819369-dad13d55-cd7d-441d-b862-2250192a036b.png)

In parallel I got also the app which I can check if the values are there present.

**Comment by Hadatko** [comment]
That means you didn't measure impedance or you have wrong sensor name in template.

**Comment by Hadatko** [comment]
Do not forget modify conditions for impedance in template

**Comment by Phoenix-DH** [comment]
Oah damn, there was a type in the weight checking to set the impendance!
Thanks for the hint. Limits/borders in the templates have been correct.

**Comment by Hadatko** [comment]
happy to help

**Comment by dckiller51** [comment]
@Hadatko I can't reproduce this error. Is she still present?

**Comment by Hadatko** [comment]
i cannot set birthday at all now 😂 which is ok ;)

**Comment by dckiller51** [comment]
> je ne peux pas du tout définir l'anniversaire maintenant 😂 ce qui est ok ;)

Please note this is not a modification available after the first creation. When you create a new user you don't have the birthday date box?

**Comment by Hadatko** [comment]
Hmm i tried it again and it looks ok now.

**Comment by iacs** [comment]
@Phoenix-DH How did you fix the calculation of impedance-based stats? They all show up as Unknown to me

**Comment by Phoenix-DH** [comment]
There is a new blueprint available:
https://github.com/dckiller51/bodymiscale/tree/main/example_config

This is what I currently use.
