### ISSUE TITLE
Is visceral_fat correct?

### ISSUE THREAD

**Issue by home409ca** [dckiller51/bodymiscale#181]
For the given data: 20.01.1992, female, height 160cm, weight 56.85, visceral_fat returns the value of 1%.

**Comment by borpin** [comment]
Yes I have seen this as well.

**Comment by dckiller51** [comment]
In my tests of the day
Female weight = 60 < 69 Height = 166 visceral_fat = 1
Female weight = 70 < 76 Height = 166 visceral_fat = 8,0
Female weight = 77 < 82 Height = 166 visceral_fat = 9,0
Female weight = 83 < 89 Height = 166 visceral_fat = 10,0

male weight = > 49 Height = 176 visceral_fat = 1
male weight = 50 Height = 176 visceral_fat = 1,0
male weight = 51 < 52 Height = 176 visceral_fat = 2,0
male weight = 53 < 54 Height = 176 visceral_fat = 3,0
male weight = 73 < 74 Height = 176 visceral_fat = 13,0

**Comment by dckiller51** [comment]
Unfortunately we all have the same source to calculate it. You should be able to uncap the latest android version of zepp life

**Comment by dckiller51** [comment]
@borpin 
I found another formula. It seems correct to me. Is it possible for you to give me the expected result for a lady? Via the official application then I would need the height, weight and impedance

**Comment by dckiller51** [comment]
update v3.1.2
