### ISSUE TITLE
Domain changed to number in HA

### ISSUE THREAD

**Issue by bonuzzz** [dckiller51/bodymiscale#188]
Regarding this commit https://github.com/dckiller51/bodymiscale/commit/e97da1668ea417a4a0f849822090c82bcedd701d ,
domain name changed from input_number to number, at least in recent home assistant versions.

**Comment by dckiller51** [comment]
> Concernant ce commit [e97da16](https://github.com/dckiller51/bodymiscale/commit/e97da1668ea417a4a0f849822090c82bcedd701d) , le nom de domaine est passé de input_number à number, du moins dans les versions récentes de Home Assistant.

I just tested in version 2023.10.0b3. I don't see any change. I created a new number entry, it remains input_number.

**Comment by bonuzzz** [comment]
I'm using the same version and I can't choose input_number entity without edit above.

<img width="443" alt="Screenshot 2023-09-30 at 20 49 22" src="https://github.com/dckiller51/bodymiscale/assets/6509127/217a54df-440f-4c67-b4de-4c6a9b3c7fa7">

**Comment by dckiller51** [comment]
![Capture d'écran 2023-10-01 012432](https://github.com/dckiller51/bodymiscale/assets/53062806/6b98c003-a8b9-431c-bebc-384809bdf992)

On the other hand, the beta version of homeassistant creates a bodymiscale.bodymiscale_bodymiscale_test_bodymiscale_2. To be continued

**Comment by dckiller51** [comment]
@bonuzzz 
Update 3.0.9 
allow input type "number" in addition to "sensor" and "input_number"
