### ISSUE TITLE
Unable to config through UI

### ISSUE THREAD

**Issue by ABUAIJUTIE** [dckiller51/bodymiscale#190]
This is my first time using this component. Thanks for your nice work~ 🎉
I downloaded it through HACS, version 3.0.8. HA runs in docker, version 2023.9.3.
When I add integration, it stuck here:
<img width="605" alt="Please wait, starting configuration wizard for bodymiscale" src="https://github.com/dckiller51/bodymiscale/assets/29325925/bf7f6ea5-0ead-4923-a7c6-5a14adc6d371">
After the looping wheel, this showed up:
<img width="417" alt="Error Window" src="https://github.com/dckiller51/bodymiscale/assets/29325925/70904661-7d5e-42ec-b08c-3b65dcbdd931">
And there is no log, I'm not able to locate the problem. 😭

**Comment by dckiller51** [comment]
@ABUAIJUTIE Did you restart homeassistant after installation?

**Comment by ABUAIJUTIE** [comment]
Yes, I restarted HA a couple times. No luck. 😭

**Comment by dckiller51** [comment]
thank you for your feedback
