### ISSUE TITLE
Home Assistant device name problem

### ISSUE THREAD

**Issue by dckiller51** [dckiller51/bodymiscale#191]
https://github.com/dckiller51/bodymiscale/blob/c239a6090f91aed2b003072cc9a71632b72166fd/custom_components/bodymiscale/entity.py#L40

@edenhaus 
In the next update, the device name changes to bodymiscale.bodymiscale_bodymiscale_aurelien_bodymiscale.
I looked on my own but there is a link with the name of the sensors. I crash everything :-)

**Comment by edenhaus** [comment]
The unique id has nothing to do with the naming. So need probably to check/verify where you set the name

**Comment by dckiller51** [comment]
@edenhaus I fixed #191. What do you think of the code? 
I still have to look at the deletion of the entity. The sensors no problem but not the bodimiscale.test entity.

**Comment by edenhaus** [comment]
Using only the description key will not work, when a user sets up this integration multiple times (multiple persons)

**Comment by dckiller51** [comment]
@edenhaus With version 3cfd2c1 normally it's good? I can't test this evening but I will continue my tests.
