### ISSUE TITLE
Can't config bodymiscale

### ISSUE THREAD

**Issue by bratmat** [dckiller51/bodymiscale#193]
I can't set a configuration of bodymiscale - I get this message after trying to add this addon {"message":"Invalid handler specified"}
How to clean old settings of bodymiscale ? I tried to remove directory and reinstaling it from hacs but no success at all. How to definitly  remove this addon with it's settings from HA ?

**Comment by dckiller51** [comment]
@bratmat

**Comment by bratmat** [comment]
I already errased this entity  :-(

**Comment by dckiller51** [comment]
delete via hacs then restart ha and then reinstall in 3.0.9

**Comment by bratmat** [comment]
Error occurred loading flow for integration bodymiscale: cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)

**Comment by dckiller51** [comment]
ah that's one of the things I touched in the last version. Are you using the latest version of HA 2023.10? otherwise you can switch to 3.0.8

**Comment by bratmat** [comment]
Home assistant core 2023.8.2
Supervisor 2023.10.0

**Comment by dckiller51** [comment]
interesting that must come from there. You can select an earlier version in hacs. 3.0.8 should work. I will update to specify that version 2023.10 is mandatory.

**Comment by bratmat** [comment]
should update core ?

**Comment by dckiller51** [comment]
That’s curious. if you have the possibility to update tried

**Comment by bratmat** [comment]
I will try it tommorow :-)

**Comment by dckiller51** [comment]
@bratmat 
Have you solved your problem?

**Comment by Scannow** [comment]
I'm having the same problem after upgrading HACS & Bodymiscale to the latest version.

Home Assistant 2023.8.4

**Comment by dckiller51** [comment]
This is what we were thinking about during our last discussions. I will put a lock on the next version. I leave it open until the update is done.

**Comment by bratmat** [comment]
> @bratmat Have you solved your problem?

Yep, updated core and everything works correctly

**Comment by dckiller51** [comment]
Update available with the minimum version required to avoid this error.
