### ISSUE TITLE
Issue with multiple Services

### ISSUE THREAD

**Issue by borpin** [dckiller51/bodymiscale#198]
Two people configured, the second is missing the Body Type sensor.

![image](https://github.com/dckiller51/bodymiscale/assets/1322749/b058fa75-aed1-47da-b8f3-8bef448077e4)

Maybe related to #169

**Comment by dckiller51** [comment]
The answer is here
[https://github.com/dckiller51/bodymiscale/blob/main/CHANGELOG.md#v307](url)
remove sensor body type from sensor but still available as attribute in component

**Comment by borpin** [comment]
Thanks. So the old sensor is not being updated then?

**Comment by dckiller51** [comment]
Yes, since the v3.0.7 [https://github.com/dckiller51/bodymiscale/blob/main/CHANGELOG.md](url)

**Comment by borpin** [comment]
Just updated and mostly fixed.
