### ISSUE TITLE
Incorrect configuration

### ISSUE THREAD

**Issue by farao780** [dckiller51/bodymiscale#2]
I tried to follow the instructions but maybe something is escaping my eyes

In configuration.yaml i put what you wrote : bodymiscale: !include components/bodymiscale.yaml  - that is invalid for a instalation through HACS. I modified to bodymiscale: !include custom_components/bodymiscale.yaml - which was accepted by HA.
I put directly into custom_components file bodymiscale.yaml in which i put the required data:

adrian:
  sensors:
    weight: sensor.adrian_w
    impedance: sensor.adrian_i
  height: 1xx
  born: "xxxxx"
  gender: "male"
  model_miscale: "181B"
wife:
  sensors:
    weight: sensor.wife_w
    impedance: sensor.wife_i
  height: 1xx
  born: "xxxxxx"
  gender: "female"
  model_miscale: "181B"  

After restart i have the following errors:

The following integrations and platforms could not be set up:

    bodymiscale

Please check your config and logs.

Logger: homeassistant.setup
Source: custom_components/bodymiscale/__init__.py:280
First occurred: 11:30:32 PM (1 occurrences)
Last logged: 11:30:32 PM
Error during setup of component bodymiscale

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/bodymiscale/__init__.py", line 114, in async_setup
    await component.async_add_entities(entities)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/bodymiscale/__init__.py", line 280, in state_attributes
    ATTR_WEIGHT: "{:.2f} kg".format(weight),
TypeError: unsupported format string passed to NoneType.__format__

Logger: homeassistant.helpers.event
Source: custom_components/bodymiscale/__init__.py:228
First occurred: 11:30:41 PM (5 occurrences)
Last logged: 11:30:43 PM

    Error while processing state changed for sensor.adrian_w
    Error while processing state changed for sensor.adrian_i
    Error while processing state changed for sensor.wife_w
    Error while processing state changed for sensor.wife_i

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 257, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 435, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/bodymiscale/__init__.py", line 168, in _state_changed_event
    self.state_changed(event.data.get("entity_id"), event.data.get("new_state"))
  File "/config/custom_components/bodymiscale/__init__.py", line 191, in state_changed
    self._update_state()
  File "/config/custom_components/bodymiscale/__init__.py", line 204, in _update_state
    result.append(self._check_max(sensor_name, value, params))
  File "/config/custom_components/bodymiscale/__init__.py", line 228, in _check_max
    if value > max_value:
TypeError: '>' not supported between instances of 'str' and 'float'

**Comment by dckiller51** [comment]
Architecture must be:

configuration.yaml
bodymiscale: !include components/bodymiscale.yaml

```
adrian:
  sensors:
    weight: sensor.adrian_w
    impedance: sensor.adrian_i
  height: 1xx
  born: "xxxx-xx-xx"
  gender: "male"
  model_miscale: "181B"
wife:
  sensors:
    weight: sensor.wife_w
    impedance: sensor.wife_i
  height: 1xx
  born: "xxxx-xx-xx"
  gender: "female"
  model_miscale: "181B"
```

Create the file bodymiscale.yaml in folder components

In folder custom_components there is the download of hacs to know
folder = bodymiscale with files 

folder \translations
__init__.py
body_metrics.py
body_scales.py
body_score.py
const.py
group.py
manifest.json
strings.json 

You will even get an error but don't worry about it. Normally the bodymiscale.adrian and bodymiscale.wife should be present

**Comment by farao780** [comment]
tried, but same errors
configuration.yaml:
bodymiscale: !include components/bodymiscale.yaml

in components/bodymiscale.yaml i have:

adrian:
  sensors:
    weight: sensor.adrian_w
    impedance: sensor.adrian_i
  height: 1xx
  born: "xxxx-xx-xx"
  gender: "male"
  model_miscale: "181B"
wife:
  sensors:
    weight: sensor.wife_w
    impedance: sensor.wife_i
  height: 1xx
  born: "xxxx-xx-xx"
  gender: "female"
  model_miscale: "181B"

in custom_components there is no init.py....is __init__.py

![2021-02-11 08_29_24-Microsoft Store](https://user-images.githubusercontent.com/74878214/107607971-520b1a00-6c43-11eb-92e6-49e2f06cb63f.png)

**Comment by dckiller51** [comment]
![file1](https://user-images.githubusercontent.com/53062806/107612431-892efa80-6c46-11eb-8a72-7465685df051.png)
![file](https://user-images.githubusercontent.com/53062806/107612433-89c79100-6c46-11eb-85a1-7ff121055dd2.png)

**Comment by farao780** [comment]
so we have the same thing, but works differently

**Comment by farao780** [comment]
The weight and impedance sensors are working fine (they were updated with my morning scaling)



![2021-02-11 10_10_51-Overview - Home Assistant](https://user-images.githubusercontent.com/74878214/107613693-7e2d9780-6c51-11eb-823e-454db2cf633b.png)

**Comment by dckiller51** [comment]
Commenter #bodymiscale: !include components/bodymiscale.yaml in confirguration.yaml

try in configuration.yaml ```
bodymiscale:
  adrian:
    sensors:
      weight: sensor.adrian_w
      impedance: sensor.adrian_i
    height: 1xx
    born: "xxxx-xx-xx"
    gender: "male"
    model_miscale: "181B"
  wife:
    sensors:
      weight: sensor.wife_w
      impedance: sensor.wife_i
    height: 1xx
    born: "xxxx-xx-xx"
    gender: "female"
    model_miscale: "181B"
```

**Comment by farao780** [comment]
unfortunately same thing
[errlog.txt](https://github.com/dckiller51/bodymiscale/files/5963921/errlog.txt)

**Comment by dckiller51** [comment]
> malheureusement même chose
> [errlog.txt](https://github.com/dckiller51/bodymiscale/files/5963921/errlog.txt)

try name esphome name: Weight Adrian

**Comment by dckiller51** [comment]
My component is created as even despite this error in my journal

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/bodymiscale/__init__.py", line 280, in state_attributes
    ATTR_WEIGHT: "{:.2f} kg".format(weight),
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by farao780** [comment]
esp name of sensor?

ok. i will try. for the moment i have:


  - platform: template
    name: Adrian_w
    id: weight_user1
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
  - platform: template
    name: Adrian_i
    id: impedance_user1
    unit_of_measurement: 'ohm'
    icon: mdi:omega

and my esphome project name is xiaomi_miscale
![esp](https://user-images.githubusercontent.com/74878214/107618829-e0d76100-6c5a-11eb-952c-e9fcc38c7c54.png)

**Comment by dckiller51** [comment]
Check as even if the bodymiscal device is created in the development tools

**Comment by farao780** [comment]
well...nice surprise: i have all calculations

![2021-02-11 11_34_17-Inbox - adrian stanciu@phoenix-it ro - Outlook](https://user-images.githubusercontent.com/74878214/107620343-36ad0880-6c5d-11eb-8179-1a2cdb469698.png)

**Comment by dckiller51** [comment]
Nice. Yes the error I cannot remove it. I am not a programmer. Complicate for me, I hope a qualified person will find out later.

**Comment by dckiller51** [comment]
Next step for me is to create a map. Here is a first draft
![Sans titre](https://user-images.githubusercontent.com/53062806/107622306-f5fec080-6c57-11eb-9713-4567a8f72e10.png)

**Comment by farao780** [comment]
u created template sensors or use a custom card to display entity attributes?

**Comment by farao780** [comment]
merci pour votre patience et votre gentillesse. J'espère qu'un programmeur résoudra les erreurs et sera une intégration réussie à 100%

**Comment by farao780** [comment]
Oh...seem i sas too happy too soon.
Arrived home and put my wife on scale and i noticed that  get entity is not
known. Maybe that generates entity error.

For me is all working.
My wife is added in same configuration file ...
Next days will try to work with ellaborate cards.

joi, 11 feb. 2021, 11:54 dckiller51 <notifications@github.com> a scris:
