### ISSUE TITLE
I made a Traditional Chinese Translation zh-Hant.json to the folder but not work?

### ISSUE THREAD

**Issue by yauyauwind** [dckiller51/bodymiscale#208]
[zh-Hant.json](https://github.com/dckiller51/bodymiscale/files/13445538/zh-Hant.json)

Hello dckiller51,

Suppose Home Assistant Traditional Chinese Code is zh-Hant or zh-tw
and I modifty your translate json and rename to zh-Hant.json
but didn't work, I switch my account to S.Chinese it can show the S.Chinese , mean the zh-Hans is work
but when I switch back to T.Chinese , it display the english language not the zh-Hant
how can I use T.Chinese in this card??

I also upload my modified zh-Hant.json for your reference

Thanks~

**Comment by yauyauwind** [comment]
Sorry I post to wrong thread

**Comment by dckiller51** [comment]
Hello, are you talking about the card or the component? Both have their own translations but are not related. For the card you generally have to switch to another language F5 on the card and the language of your choice F5. If you are using hacs, I advise you to remove the map and install it manually. I have already encountered the fact that hacs keeps the original version in memory. Last thing modification do you need, I can just add and update it for the community.

**Comment by yauyauwind** [comment]
Hello dckiller51,

I tried remove the body miscale card from hacs, then manual to install the card
but still haven't Traditional Chinese showed, but S.Chinese can be showed
and yes, please help to add the T.Chinese to the next version, so that I can use the T.Chinese

Many Thanks~~~

**Comment by dckiller51** [comment]
Sorry, I misread. I'm going to push the version for the components but can you also do it for the card. See the link.

[Translate Card](https://github.com/dckiller51/lovelace-body-miscale-card/tree/main/src/localize/languages)

**Comment by dckiller51** [comment]
@yauyauwind Update available
![Capture d'écran 2023-11-23 150027](https://github.com/dckiller51/bodymiscale/assets/53062806/1557970b-ab9e-465f-b5cb-856cc53a8f4f)

**Comment by yauyauwind** [comment]
Hello dckiller51,

Ha... XD , sorry my fault....
I can only see the custom components of body with translation folder custom_components\bodymiscale\translations

However I want the card can support T.Chinese too
but card is .js only

[zh-Hant.json](https://github.com/dckiller51/bodymiscale/files/13454523/zh-Hant.json)

and I modified the card with T.Chinese
please help to update the card

And sorry again, please accept my apologies

Thanks~

**Comment by dckiller51** [comment]
@yauyauwind Update available.
good day

**Comment by yauyauwind** [comment]
Hello dckiller51,

Work perfectly, Thank you so much~
