### ISSUE TITLE
Incorrect womens calculations

### ISSUE THREAD

**Issue by luigi311** [dckiller51/bodymiscale#221]
Looks like there are some issues with the womens calculations, male seems spot on as all my numbers are correct but my SO some of the numbers are off by a significant amount. I can provide you a list of what zepp reports and what this is reporting if needed via email so i dont paste it all in here since i doubt she would like that lol, email me at git@luigi311.com

Visceral Fat is off by 4
Body fat by 11
protein by 3
water by 8
muscle mass by 19
ideal by 5
basal metabolism by 323
metabolic age by 20

**Comment by dckiller51** [comment]
Hi, thanks for your data. After checking your ZEPP data corresponds to the male equivalent and not for a woman.
Can you check again in your application?

**Comment by dckiller51** [comment]
@luigi311 Hello, were you able to check your Zepp application?

**Comment by dckiller51** [comment]
@luigi311 
Hi, I just did my own tests. I don't see any problems. I'm going to close post. I enclose my tests. 

Consolidation of results
![Comparatif](https://github.com/dckiller51/bodymiscale/assets/53062806/83c4bda5-ae6a-44cc-aa15-4c23c41f03e1)

ZEPP Man
![Zepp Man](https://github.com/dckiller51/bodymiscale/assets/53062806/b030ff40-ea0b-4f59-a400-8561dee3a85e)

Bodymiscale Man
![Bodymiscale Man](https://github.com/dckiller51/bodymiscale/assets/53062806/1f05f910-b4e1-47f6-8910-3d6cefc89c23)

ZEPP Woman
![ZEPP Woman](https://github.com/dckiller51/bodymiscale/assets/53062806/4104ac42-4364-4581-8874-5147c3d4c3ec)

Bodymiscale Woman
![Bodymiscale Woman](https://github.com/dckiller51/bodymiscale/assets/53062806/376798d9-74ab-40ee-848b-bdb00ec8418c)
