### ISSUE TITLE
Custom components

### ISSUE THREAD

**Issue by Asarria081** [dckiller51/bodymiscale#23]
I´ve done the BLE configuration in ESPHome and now I´ve two sensors (weight and impedance) working in my HA. I also installed your custom component and configurated the file bodymiscale.yaml. However the sensors created at bodmiyscale.yaml doesn´t show me any information about weight and impedance.
Should these sensors been vinculated to ESPHome sensors somehow?? In afirmative case, what should I do to get it?
Thanks

**Comment by dckiller51** [comment]
yes you must put your sensor. (weight) and sensor. (impedance)

**Comment by Asarria081** [comment]
I don´t know what do you mean. 
This is my configuration for the BLE tracker in ESPHOME:

- platform: xiaomi_miscale2
    mac_address: 'XX:XX:XX:XX:XX:XX'
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: weight_miscale
    impedance:
      name: "Xiaomi Mi Scale Impedance"
      id: impedance_xiaomi
             

  - platform: template
    name: Peso Wafa
    id: weight_wafa
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2

Then, what must be the configuration for the bodymiscale.yaml??

**Comment by dckiller51** [comment]
https://github.com/dckiller51/bodymiscale#example

**Comment by edenhaus** [comment]
Closing due inactivity
