### ISSUE TITLE
A bug since version 2024.6.0

### ISSUE THREAD

**Issue by Toolmaster30** [dckiller51/bodymiscale#234]
Since the last update of Home Assistant to version 2024.6.0, the following error has occurred.

`Logger: homeassistant.util.logging
Quelle: util/logging.py:95
Erstmals aufgetreten: 07:12:21 (1 Vorkommnisse)
Zuletzt protokolliert: 07:12:21

Exception in <function _process_group_platform at 0x7fbc386ce980> when processing platform 'group': (<HomeAssistant NOT_RUNNING>, 'bodymiscale', <module 'custom_components.bodymiscale.group' from '/config/custom_components/bodymiscale/group.py'>) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/group/registry.py", line 44, in _process_group_platform platform.async_describe_on_off_states(hass, registry) File "/config/custom_components/bodymiscale/group.py", line 14, in async_describe_on_off_states registry.on_off_states({STATE_PROBLEM}, STATE_OK) TypeError: GroupIntegrationRegistry.on_off_states() missing 2 required positional arguments: 'default_on_state' and 'off_state'`

**Comment by dckiller51** [comment]
Update available
