### ISSUE TITLE
expose the computed attributes as sensors

### ISSUE THREAD

**Issue by alinelena** [dckiller51/bodymiscale#24]
This is more a question.
is it possible to expose some of the attributes as sensors? the idea is to plan them

**Comment by dckiller51** [comment]
> C'est plus une question.
> est-il possible d'exposer certains des attributs en tant que capteurs ? l'idée est de les planifier

https://github.com/dckiller51/lovelace-body-miscale-card/issues/8#issuecomment-893319547

**Comment by alinelena** [comment]
Merci! Idea was to plot I did not realise I missed that issue already

**Comment by alinelena** [comment]
i will close this and continue to the original since seems to be the same.
