### ISSUE TITLE
visceral fat different from the one computed by xiaomi app

### ISSUE THREAD

**Issue by alinelena** [dckiller51/bodymiscale#27]
i really do not know where the formulae come from for this but the numbers are different between xiaomi app and what is computed in python for me for example app gives 13 and the ha component 17.

this is odd since all the rest are more or less the same

**Comment by alinelena** [comment]
happy to look into it if the re process is described somewhere

**Comment by dckiller51** [comment]
file retrieval from the net.

**Comment by alinelena** [comment]
do you have a source for that? I can look into it and check the formulae. practically this and body score seem to be the only ones which are off compared with the scale...

**Comment by dckiller51** [comment]
Source example
source 1
[https://github.com/lolouk44/xiaomi_mi_scale/tree/master/src](url)

source 2
[https://github.com/oliexdev/openScale](url)
problem [https://github.com/oliexdev/openScale/issues/597](url)
interesting information [https://github.com/oliexdev/openScale/issues/412](url)

One should look at the latest mifit apk and search libBodyfat.so

I watch tonight on my way home

**Comment by alinelena** [comment]
thanks I think I may get it what is wrong, I will go through the code and try to fix it...

**Comment by alinelena** [comment]
ok so I looked into this
https://github.com/oliexdev/openScale/blob/master/android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/MiScaleLib.java

and seems to have implemented the same formula, I suspect openscale will have the same issue.

**Comment by dckiller51** [comment]
Another calculation here

https://github.com/oliexdev/openScale/blob/2935191e05d5faa12c353094385aaebf7dc7395e/android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/YunmaiLib.java#L118

**Comment by alinelena** [comment]
personally I think these numbers tend to be gibberish but if we want them to match the scales we need to match the the mi fit app... I extracted the apk yesterday but formulae are a little bit too much I never did for java stuff.

**Comment by dckiller51** [comment]
> personally I think these numbers tend to be gibberish but if we want them to match the scales we need to match the the mi fit app... I extracted the apk yesterday but formulae are a little bit too much I never did for java stuff.

Maybe this formula is more suitable?

https://www.calculator.net/body-fat-calculator.html

BMI Method:

Another method for calculating an estimate of body fat percentage uses BMI. Refer to the BMI Calculator to obtain an estimate of BMI for use with the BMI method, as well as further detail on how BMI is calculated, its implications, and its limitations. Briefly, the estimation of BMI involves the use of formulas that require the measurement of a person's height and weight. Given BMI, the following formulas can be used to estimate a person's body fat percentage.

Body fat percentage (BFP) formula for adult males:
BFP = 1.20 × BMI + 0.23 × Age - 16.2
Body fat percentage (BFP) formula for adult females:
BFP = 1.20 × BMI + 0.23 × Age - 5.4

**Comment by FredFreegroup** [comment]
Found huge difference between yours and MIScale data
weight 56.7 kg
impedance 607
height 162 cm
born year 1967
female

visceral_fat
Mi - 6.0
sensor.xxxx_visceral_fat  1

and few other differences

body_fat	
27.73	
29.2	

muscle	
38.9	
38.03	

moisture
49.58
50.5

score
83
91

metabolic age
42
40

protein
19.02
16.5

**Comment by adolfonovo** [comment]
Yeah, me too, for example the metabolic age. There is no change and very diferrent from the app

**Comment by menloperk** [comment]
I got here since integration is not working anymore since last update to 2023.7.0 but other long standing problem is that the value for 'Visceral fat' just can't be right. This has been bugging me for quite a while. For me it reads 20 or 21 which just can't be right at all. I had been trying to Google some time ago to see if Xiaomi had a different definition but I now suspect there is something wrong with the calculations done in this integration.

**Comment by dckiller51** [comment]
update v3.1.2
