### ISSUE TITLE
TypeError: unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by lrswss** [dckiller51/bodymiscale#3]
Just installed your component using HACS on HA 2021.2.3 running in Docker. On startup I get the following stack trace:

```
2021-03-07 14:23:05 ERROR (MainThread) [homeassistant.setup] Error during setup of component bodymiscale
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/bodymiscale/__init__.py", line 114, in async_setup
    await component.async_add_entities(entities)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/bodymiscale/__init__.py", line 280, in state_attributes
    ATTR_WEIGHT: "{:.2f} kg".format(weight),
TypeError: unsupported format string passed to NoneType.__format__
```
```
docker@bpi2:~/homeassistant/config $ docker exec -it 1bba12d5fffb bash
bash-5.0# python3 --version
Python 3.8.7
```

**Comment by dckiller51** [comment]
i cant fix this error but normally you should have your bodyscale.xxxx to create.

**Comment by dckiller51** [comment]
> Just installed your component using HACS on HA 2021.2.3 running in Docker. On startup I get the following stack trace:
> 
> ```
> 2021-03-07 14:23:05 ERROR (MainThread) [homeassistant.setup] Error during setup of component bodymiscale
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
>     result = await task
>   File "/config/custom_components/bodymiscale/__init__.py", line 114, in async_setup
>     await component.async_add_entities(entities)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
>     attr.update(self.state_attributes or {})
>   File "/config/custom_components/bodymiscale/__init__.py", line 280, in state_attributes
>     ATTR_WEIGHT: "{:.2f} kg".format(weight),
> TypeError: unsupported format string passed to NoneType.__format__
> ```
> 
> ```
> docker@bpi2:~/homeassistant/config $ docker exec -it 1bba12d5fffb bash
> bash-5.0# python3 --version
> Python 3.8.7
> ```

i cant fix this error but normally you should have your bodyscale.xxxx to create.

**Comment by dckiller51** [comment]
@lrswss can you tell us where are you?

**Comment by lrswss** [comment]
I eventually got everything running. The error is still present upon startup but doesn't seem to have any further impact. Data from the scale is posted to HA as expected.

**Comment by dckiller51** [comment]
> J'ai fini par tout faire fonctionner. L'erreur est toujours présente au démarrage mais ne semble pas avoir d'impact supplémentaire. Les données de la balance sont publiées dans HA comme prévu.

Great. I hope that a developer will find a solution. otherwise I will soon share a map.
