### ISSUE TITLE
Details are not visible.

### ISSUE THREAD

**Issue by emre299** [dckiller51/bodymiscale#33]
Hi, my settings are as below, I am using ras pi4 ble and mi scale2.
Where am I going wrong, thanks.

![3](https://user-images.githubusercontent.com/32033063/132955232-c78d30fb-a260-4200-9809-5422257861e3.PNG)
![2](https://user-images.githubusercontent.com/32033063/132955234-fcfc1218-544e-4c15-b111-ada2b88ecac2.PNG)
![1](https://user-images.githubusercontent.com/32033063/132955235-7269c36b-6f6a-4726-b299-9b63ea2f8ee2.PNG)

**Comment by dckiller51** [comment]
> Hi, my settings are as below, I am using ras pi4 ble and mi scale2.
> Where am I going wrong, thanks.
> 
> ![3](https://user-images.githubusercontent.com/32033063/132955232-c78d30fb-a260-4200-9809-5422257861e3.PNG)
> ![2](https://user-images.githubusercontent.com/32033063/132955234-fcfc1218-544e-4c15-b111-ada2b88ecac2.PNG)
> ![1](https://user-images.githubusercontent.com/32033063/132955235-7269c36b-6f6a-4726-b299-9b63ea2f8ee2.PNG)

The problem comes from your 2 sensors. To replace for test :

weight: sensor.weight_mi_scale2  to 
weight: sensor.ble_weight_09c541e6e096

impedance: sensor.impedance_mi_scale2
impedance :

**Comment by dckiller51** [comment]
You must replace with your user sensors

**Comment by emre299** [comment]
It's my fault, I did what you said. Thanks, problem solved.
