### ISSUE TITLE
Clarify Date of Birth Format and age calculation

### ISSUE THREAD

**Issue by borpin** [dckiller51/bodymiscale#43]
In the docs please clarify if the DOB is YYY-MM-DD or YYY-DD-MM.

Neither format calculates the age correctly when DOB is 7th Dec 1964.

**Comment by borpin** [comment]
https://github.com/dckiller51/bodymiscale/blob/676acf2abea8bfcc0e6c81ba63a36ad6655b3f90/custom_components/bodymiscale/__init__.py#L159-L165

**Comment by dckiller51** [comment]
hello, you are right your solution is good. Thank you for your contribution. I'll be releasing the update this weekend.

**Comment by dckiller51** [comment]
update available v1.1.4
