### ISSUE TITLE
Double reports if the two sensors are updated at different times

### ISSUE THREAD

**Issue by borpin** [dckiller51/bodymiscale#51]
I am occasionally seeing double reports from the component within a few milliseconds of each other.

I wonder if this is caused by the 2 sensors being updated at slightly different times?

Does the component wait for both sensors to be updated before doing the calculations?

**Comment by borpin** [comment]
@dckiller51 I have worked with the author of the Passive BLE Monitor integration such that the weight and impedance sensors update almost simultaneously.  https://github.com/custom-components/ble_monitor/issues/617

However, I am still getting 2 updates of this component. All I can think of is that the few milliseconds between the 2 sensors update is sufficient to trigger the 2 updates.

Can a delay be added in while the component waits for both sensors to update?

**Comment by edenhaus** [comment]
Currently the component subscribe for states updates for each sensor.

On each sensor update all values are calculated.
https://github.com/dckiller51/bodymiscale/blob/d5c03bffad048fb431af9485fd58173e7f385082/custom_components/bodymiscale/__init__.py#L237-L244

To avoid the second report, we need to change how we subscribe. Probably introduce a delay

**Comment by borpin** [comment]
Precisely and you cannot calculate the correct details until both the `weight` and the `impedance` are available.
