### ISSUE TITLE
Request for support HUAWEI AH100 Scale

### ISSUE THREAD

**Issue by tanker11** [dckiller51/bodymiscale#52]
Hello,

I have a Huawei AH100 scale, with very similar parameters to the Xiaomi described.
Would it be possible to integrate it?
Can I do it manually or could I contribute by provididng more data, testing etc?

Thanks in advance,
Robert

**Comment by dckiller51** [comment]
Hello, the components does not recover bluetooth data. With the Xiaomi we recover the data either via Esphome or Bluetooth monitor.

**Comment by tanker11** [comment]
Sorry, this is not clear to me. Does it mean you have no plans to support it?

**Comment by dckiller51** [comment]
You have to look there to get your data back. https://community.home-assistant.io/t/passive-ble-monitor-integration-xiaomi-mijia-ble-mibeacon-monitor/177352

Then you can use Bodymiscale.
