### ISSUE TITLE
Impedance and Weight are stored in the DB only for 10 days

### ISSUE THREAD

**Issue by FPMilan** [dckiller51/bodymiscale#55]
Hi,
When I wanted to look at my weight development over the past months I realized that the weight and impedance are stored only for 10 days. 

Is this an error in my installation or is this intended?

The point in having this integration in the first place is for me to see how I develop over time. Would highly appreciate if this can be changed

KR
Milan

**Comment by dckiller51** [comment]
I think there is no link with the bodymiscale.

**Comment by Doublemyst** [comment]
I have the same question. I just installed it, and I wanted to somehow display the development. Is there a way to store the measured data for years?

**Comment by edenhaus** [comment]
How long they are stored in the DB has nothing to do with this component.
On the recorder integration you can change the [`purge_keep_days`](https://www.home-assistant.io/integrations/recorder/#purge_keep_days) settings, which has as default 10 days.
Please be aware that depending on our system increasing this value can have negative affects.
