### ISSUE TITLE
v 1.1.5 what does "Convert Weight" mean?

### ISSUE THREAD

**Issue by borpin** [dckiller51/bodymiscale#56]
The release notes for 1.1.5 https://github.com/dckiller51/bodymiscale#v115 state:

"Convert weight from lbs to kgs"

Where and what? The output, the input?

Pretty major change and probably a breaking change.

Note the Docs do **not** state the weight measurement system in use (has to be guessed).

**Comment by dckiller51** [comment]
Hello, it's just if your scale is set to lbs then it does the conversion to kg for the calculations.

**Comment by borpin** [comment]
How does it know if the input figure is pounds or kg?

**Comment by dckiller51** [comment]
To set the scale in kg or lbs you must use the mifit application. Then for example if I weigh 75kg the scale displays 167 lbs.

**Comment by borpin** [comment]
I mean how does the integration know if the weight measurement it is sent, is in kg or lbs?

I am presuming that if you change the display, it changes the units the scale sends the data in (never used the app).

**Comment by borpin** [comment]
> You must specify it in your weight sensor

I suggest adding that to the documentation. Also is there a default it falls back to? what if there is no `unit_of_measurment` in the sensor? How does it handle that?

Cheers

**Comment by dckiller51** [comment]
This is not a requirement. By default it remains in kg. To have fun, you can do the test by adding an input_number as sensor weight.

**Comment by borpin** [comment]
Ok thanks.
