### ISSUE TITLE
Add units to the Readme for the generated data

### ISSUE THREAD

**Issue by borpin** [dckiller51/bodymiscale#57]
Could the ReadMe be updated with the units of measurement that the generated data is in, please?

e.g weight (lbs or kg), bone mass etc.

**Comment by dckiller51** [comment]
Je viens de mettre à jour le redame. Cela vous semble t-il plus compréhensible ?

**Comment by borpin** [comment]
Ah OK, I had thought you might add it to the table of attributes.

Small point - the SI unit is kg (not KG). 😀 

Thanks.

**Comment by lisankai93** [comment]
Please add the unit of the generated data as below:

    Weight (kg)
    Height (cm)
    Basal metabolism (%?)
    Visceral fat (kg?)
    Ideal weight (kg?)
    Lean body mass (kg?)
    Body fat (kg?)
    Water (kg? or %?)
    Bone mass (kg?)
    Muscle mass (kg?)
    Fat mass ideal (kg?)
    Protein (kg? or %?)

Many thanks!

**Comment by lisankai93** [comment]
> Please add the unit of the generated data as below:
> 
> ```
> Weight (kg)
> Height (cm)
> Basal metabolism (%?)
> Visceral fat (kg?)
> Ideal weight (kg?)
> Lean body mass (kg?)
> Body fat (kg?)
> Water (kg? or %?)
> Bone mass (kg?)
> Muscle mass (kg?)
> Fat mass ideal (kg?)
> Protein (kg? or %?)
> ```
> 
> Many thanks!

It would be even better if the explanation and relationship of the above indicators could be obtained.

**Comment by edenhaus** [comment]
> Weight (kg)
> Height (cm)
> Basal metabolism (%?)
> Visceral fat (kg?)
> Ideal weight (kg?)
> Lean body mass (kg?)
> Body fat (kg?)
> Water (kg? or %?)
> Bone mass (kg?)
> Muscle mass (kg?)
> Fat mass ideal (kg?)
> Protein (kg? or %?)

@dckiller51 Can you confirm this values? I would add the units to the new sensors

**Comment by dckiller51** [comment]
![IMG_20220410_231132](https://user-images.githubusercontent.com/53062806/162640071-41464371-c5da-45c9-8f86-949d5f8bd4f8.jpg)
This corresponds to the equivalent of the xiaomi application.

**Comment by lisankai93** [comment]
> ![IMG_20220410_231132](https://user-images.githubusercontent.com/53062806/162640071-41464371-c5da-45c9-8f86-949d5f8bd4f8.jpg) This corresponds to the equivalent of the xiaomi application.

Got it, thanks!
