### ISSUE TITLE
Dev questions

### ISSUE THREAD

**Issue by edenhaus** [dckiller51/bodymiscale#61]
Hi @dckiller51,

first thank for this component. Currently I prepare the PR to add config flow for this component and I got some questions:

- In https://github.com/home-assistant/brands/pull/2818#issuecomment-924643156 you say that the component can be used by any scale (I agree with you), so I suggest to rename to component to `bodyscale` or what do you think?
- I will also remove the option scale model as we don't need it. If the use configures the impedance sensor, we calculate more attributes.
- Are the configuration options `min_weight`, `max_weight`, `min_impedance`, `max_impedance` still used? There is no documentation about it and I suggest to remove them. I understand why you introduced them, but if there are two persons, we need to separate their readings outside this component (examples [esphome](https://esphome.io/components/sensor/xiaomi_miscale.html#configuration-example-with-multiple-users), #11) and therefore these config options are useless imo.

After I have added the config flow support, it easy to add a sensor for each attribute (#40) and also fix #39, #37, #25.
What do you think?

**Comment by dckiller51** [comment]
Hello ,
I don't have a problem with the changes but it must be compatible with the card that goes with it https://github.com/dckiller51/lovelace-body-miscale-card. 

For the configuration options min_weight, max_weight, min_impedance, max_impedance it allows to have a quick state.
https://community-assets.home-assistant.io/original/3X/a/c/ac505f58d1c54e97f02f633ae2b379ff9c7d66ef.png

**Comment by edenhaus** [comment]
> I don't have a problem with the changes but it must be compatible with the card that goes with it https://github.com/dckiller51/lovelace-body-miscale-card.

That's of course, I use also this card :) The entity stays at it is only new will be added.

> For the configuration options min_weight, max_weight, min_impedance, max_impedance it allows to have a quick state.
> https://community-assets.home-assistant.io/original/3X/a/c/ac505f58d1c54e97f02f633ae2b379ff9c7d66ef.png

Sorry I didn't understand it. I understand, that when they impedance is negative it is not a valid value and therefore still a "impedance low" error state will be created. I would only delete the ability for the user to change this values and internal use the default values as specified in `const.py`
https://github.com/dckiller51/bodymiscale/blob/d5c03bffad048fb431af9485fd58173e7f385082/custom_components/bodymiscale/const.py#L53-L56

**Comment by dckiller51** [comment]
Ok I thought you wanted to delete it. we can actually put it in hard.

**Comment by edenhaus** [comment]
> I don't have a problem with the changes but it must be compatible with the card that goes with it https://github.com/dckiller51/lovelace-body-miscale-card.

We probably need also adjust the card in the future as HA development guidelines are saying the following:
![grafik](https://user-images.githubusercontent.com/26537646/162566537-9fc42e0a-bf4c-4adb-8834-fe8a2f8b1be7.png)
https://developers.home-assistant.io/docs/core/entity#generic-properties

So probably after I have created a sensor for each attribute, we should adapt the card to use the new sensors and afterwards remove the old bodymiscale entity completely.

We don't have to hurry, but we should keep it on the radar.
