### ISSUE TITLE
V2.1.0 no input for Birthday "apple iOS"

### ISSUE THREAD

**Issue by TobsenHH** [dckiller51/bodymiscale#76]
no input field for birthday

<img width="586" alt="Bildschirmfoto 2022-04-13 um 12 57 54" src="https://user-images.githubusercontent.com/83597390/163166230-57f5812d-8baa-4b1d-b2c6-5e424c767f1b.png">

**Comment by aetha** [comment]
Subscribing, I get the same issue.

**Comment by dckiller51** [comment]
Do you have version 2022.4.0.b0 at least? 
Did you have the choice of the date before the error message? 
Do not enter the date manually, otherwise you will get this error message. 
You can click on the years for a quick selection.

**Comment by edenhaus** [comment]
This issue exists only on the iPhones and not on the iPad. Very strange...

**Comment by TobsenHH** [comment]
I use a MacBook with safari, I try it with Firefox on my MacBook

**Comment by lazodar** [comment]
Probably unrelated, but it would be nice to be able to use it as a slightly older person... I can not pick my birthdate because I was born before 1970... Date picker does not go further back then 01-01-1970?

**Comment by dckiller51** [comment]
> This issue exists only on the iPhones and not on the iPad. Very strange...

I have an old Ipad, on safari I also have the problem. On the other hand when I change the selector to datetime it loads correctly.
```
selector({"datetime": {}}),
```
