### ISSUE TITLE
Date picker don't allow to select a date before 01.01.1970

### ISSUE THREAD

**Issue by edenhaus** [dckiller51/bodymiscale#78]
I can not pick my birthdate because I was born before 1970... Date picker does not go further back then 01-01-1970?

_Originally posted by @lazodar in https://github.com/dckiller51/bodymiscale/issues/76#issuecomment-1099123083_

**Comment by edenhaus** [comment]
@dckiller51 Should we revert to a textbox, where the user needs to insert the date? Will probably both problems

**Comment by dckiller51** [comment]
You are right, it will be easier.
